panda series

creating series

In [1]:
import numpy as np 
import pandas as pd

In [2]:
arr = np.array([1,2,3,4])
labels = [ 'a' , 'b' , 'c' , 'd']

In [3]:
pd.Series(arr)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
pd.Series(arr,index=labels)

a    1
b    2
c    3
d    4
dtype: int64

DATAFRAMES

CREATING DATAFRAMES

In [5]:
data = {
    'name' : ['kartik' , 'himanshu'],
'age' : [20 , 20 ],
'city' : ['ghaziabad' , 'ghaziabad ' ]

}

In [6]:
data

{'name': ['kartik', 'himanshu'],
 'age': [20, 20],
 'city': ['ghaziabad', 'ghaziabad ']}

In [7]:
pd.DataFrame(data)

       name  age        city
0    kartik   20   ghaziabad
1  himanshu   20  ghaziabad

In [8]:

data2 = [
     ['kartik' , 20 ,'govindpuram'],
    ['himanshu', 20 , 'noida']

]
pd.DataFrame(data2)

          0   1            2
0    kartik  20  govindpuram
1  himanshu  20        noida

In [9]:
column_name = ['name' , 'age' , 'city ']
df=pd.DataFrame(data2,columns = column_name)
df

       name  age        city
0    kartik   20  govindpuram
1  himanshu   20        noida

select and indexing of columns

In [10]:
df['name']

0      kartik
1    himanshu
Name: name, dtype: str

creating a new column

In [11]:
df ['destination ']=['data anlyst ' , 'backend doveloper']

In [12]:
df

       name  age        city        destination
0    kartik   20  govindpuram       data anlyst
1  himanshu   20        noida  backend doveloper

Remove columns

In [13]:
df.drop('destination ',axis=1)

       name  age        city
0    kartik   20  govindpuram
1  himanshu   20        noida

for permanenet remove

In [14]:
df

       name  age        city        destination
0    kartik   20  govindpuram       data anlyst
1  himanshu   20        noida  backend doveloper

SELECTING ROW

In [15]:
df.loc[0]

name                  kartik
age                       20
city             govindpuram
destination     data anlyst
Name: 0, dtype: object

In [16]:
df.loc[[0,1]]

       name  age        city        destination
0    kartik   20  govindpuram       data anlyst
1  himanshu   20        noida  backend doveloper

subsets of row and columns

In [17]:
df.loc[0][['name' ,'age']]

name    kartik
age         20
Name: 0, dtype: object

conditional selection

In [18]:
df[df['name']=='kartik']

     name  age        city   destination
0  kartik   20  govindpuram  data anlyst

missing data

In [19]:
missing_data = {
    'A' : [1,2,np.nan , 3 ,4 ] ,
'B' : [5, 6, 7,8,9 ],
'C' : [np.nan , 9 ,10 , 11 , 12 ] ,
'D' : [ 13, np.nan , 14 , 15 , 16]
}
mdf=pd.DataFrame(missing_data)

In [20]:
mdf

     A  B     C     D
0  1.0  5   NaN  13.0
1  2.0  6   9.0   NaN
2  NaN  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

In [21]:
mdf.isna()

       A      B      C      D
0  False  False   True  False
1  False  False  False   True
2   True  False  False  False
3  False  False  False  False
4  False  False  False  False

In [22]:
mdf.isna().sum()

A    1
B    0
C    1
D    1
dtype: int64

In [23]:
mdf.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

removing missing data

In [24]:
mdf

     A  B     C     D
0  1.0  5   NaN  13.0
1  2.0  6   9.0   NaN
2  NaN  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

In [25]:
mdf.dropna()

     A  B     C     D
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

In [26]:
mdf.dropna(thresh=3)

     A  B     C     D
0  1.0  5   NaN  13.0
1  2.0  6   9.0   NaN
2  NaN  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

filling the missing number

In [27]:
mdf

     A  B     C     D
0  1.0  5   NaN  13.0
1  2.0  6   9.0   NaN
2  NaN  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

In [28]:
mdf.fillna(0)

     A  B     C     D
0  1.0  5   0.0  13.0
1  2.0  6   9.0   0.0
2  0.0  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

In [29]:
values={'A':1 ,'D':2 , 'C': 4 }
mdf.fillna(value=values)

     A  B     C     D
0  1.0  5   4.0  13.0
1  2.0  6   9.0   2.0
2  1.0  7  10.0  14.0
3  3.0  8  11.0  15.0
4  4.0  9  12.0  16.0

merging , joining and concatenation

merge 2 data frame

In [30]:
df1=pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['kartik','himanshu','kritika','ayushi','shivam'],
    'department':['da','bd','fashion','hr','ca']
        })
df2=pd.DataFrame({
    'id':[1,2,3,6,7],
    'salary':['12lpa','10lpa',7,15,9],
    'bonus':[20000,50000,2000,900000,30000]
        })

In [31]:
df1

   id      name department
0   1    kartik         da
1   2  himanshu         bd
2   3   kritika    fashion
3   4    ayushi         hr
4   5    shivam         ca

In [32]:
df2

   id salary   bonus
0   1  12lpa   20000
1   2  10lpa   50000
2   3      7    2000
3   6     15  900000
4   7      9   30000

In [33]:
 pd.merge(df1,df2)

   id      name department salary  bonus
0   1    kartik         da  12lpa  20000
1   2  himanshu         bd  10lpa  50000
2   3   kritika    fashion      7   2000

In [34]:
pd.merge(df1,df2,on='id',how='inner')

   id      name department salary  bonus
0   1    kartik         da  12lpa  20000
1   2  himanshu         bd  10lpa  50000
2   3   kritika    fashion      7   2000

In [35]:
pd.merge(df1,df2,on='id',how='outer')

   id      name department salary     bonus
0   1    kartik         da  12lpa   20000.0
1   2  himanshu         bd  10lpa   50000.0
2   3   kritika    fashion      7    2000.0
3   4    ayushi         hr    NaN       NaN
4   5    shivam         ca    NaN       NaN
5   6       NaN        NaN     15  900000.0
6   7       NaN        NaN      9   30000.0

In [36]:
pd.merge(df1,df2,on='id',how='left')

   id      name department salary    bonus
0   1    kartik         da  12lpa  20000.0
1   2  himanshu         bd  10lpa  50000.0
2   3   kritika    fashion      7   2000.0
3   4    ayushi         hr    NaN      NaN
4   5    shivam         ca    NaN      NaN

In [37]:
pd.merge(df1,df2,on='id',how='right')

   id      name department salary   bonus
0   1    kartik         da  12lpa   20000
1   2  himanshu         bd  10lpa   50000
2   3   kritika    fashion      7    2000
3   6       NaN        NaN     15  900000
4   7       NaN        NaN      9   30000

concatenation of 2 dataframe

In [38]:
cpd1=pd.DataFrame({
    'A':['A0','A1','A2'],
       'B':['B0','B1','B2'],
       'C':['C0','C1','C2']
})
cpd2=pd.DataFrame({
    'A':['A3','A4','A5'],
       'B':['B3','B4','B5'],
       'C':['C3','C4','C5']
})

In [39]:
cpd1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [40]:
cpd2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [41]:
pd.concat([cpd1,cpd2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [42]:
pd.concat([cpd1,cpd2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

joining 2 dataframe

In [43]:
jdf1=pd.DataFrame({
    'name':['kartik','himanshu','ayushi']
} , index=[1,2,3] )
jdf2=pd.DataFrame({
    'scores':[9 , 6 , 9.5 ] 
} , index = [2,3,4])

In [44]:
jdf1

       name
1    kartik
2  himanshu
3    ayushi

In [45]:
jdf2

   scores
2     9.0
3     6.0
4     9.5

In [46]:
jdf1.join(jdf2)

       name  scores
1    kartik     NaN
2  himanshu     9.0
3    ayushi     6.0

In [47]:
jdf1.join(jdf2,how='outer')

       name  scores
1    kartik     NaN
2  himanshu     9.0
3    ayushi     6.0
4       NaN     9.5

Group by and agrregession

Group by

In [48]:
gdf = pd.DataFrame({
    'category': ['A','B','B','A','B','A','A','B'],
    'stores': ['S1','S2','S2','S1','S2','S1','S1','S2'],
    'Sales': [100,150,200,100,400,300,50,70],
    'Quantity': [10,15,5,20,50,40,30,20],
    'date': pd.date_range('2023-01-01', periods=8)
})

gdf

  category stores  Sales  Quantity       date
0        A     S1    100        10 2023-01-01
1        B     S2    150        15 2023-01-02
2        B     S2    200         5 2023-01-03
3        A     S1    100        20 2023-01-04
4        B     S2    400        50 2023-01-05
5        A     S1    300        40 2023-01-06
6        A     S1     50        30 2023-01-07
7        B     S2     70        20 2023-01-08

In [49]:
#gruob by category and sum of sales
cat= gdf.groupby('category')['Sales'].sum()

In [50]:
cat

category
A    550
B    820
Name: Sales, dtype: int64

In [51]:
#group by stores and sum of sales
sat=gdf.groupby('stores')['Sales'].sum()

In [52]:
#group by category and stores and sum of sales
gs=gdf.groupby(['category','stores'])['Sales'].sum()

In [53]:
gs

category  stores
A         S1        550
B         S2        820
Name: Sales, dtype: int64

In [54]:
sat

stores
S1    550
S2    820
Name: Sales, dtype: int64

agrregation

In [55]:
gdf['Sales'].mean()

np.float64(171.25)

In [56]:
gdf['Sales'].agg(['sum','median','mean','min','max','count','std'])

sum       1370.000000
median     125.000000
mean       171.250000
min         50.000000
max        400.000000
count        8.000000
std        122.642046
Name: Sales, dtype: float64

pivot table

In [57]:
pivot_data = {
    'Date': [
        '2023-01-01','2023-01-02','2023-01-03','2023-01-04','2023-01-05',
        '2023-01-06','2023-01-07','2023-01-08','2023-01-09','2023-01-10',
        '2023-01-11','2023-01-12','2023-01-13','2023-01-14','2023-01-15',
        '2023-01-16','2023-01-17','2023-01-18','2023-01-19','2023-01-20'
    ],

    'Product': [
        'A','B','C','D','A',
        'B','C','D','A','B',
        'C','D','A','B','C',
        'D','A','B','C','D'
    ],

    'Region': [
        'East','West','North','South','East',
        'West','North','South','East','West',
        'North','South','East','West','North',
        'South','East','West','North','South'
    ],

    'Sales': [
        450, 780, 320, 910, 560,
        670, 230, 850, 490, 720,
        380, 640, 590, 810, 270,
        930, 410, 760, 350, 880
    ],

    'Units': [
        25, 45, 18, 52, 31,
        39, 15, 48, 28, 42,
        21, 35, 33, 46, 17,
        55, 24, 41, 20, 50
    ],

    'Rep': [
        'John','Mary','Bob','Alice','John',
        'Mary','Bob','Alice','John','Mary',
        'Bob','Alice','John','Mary','Bob',
        'Alice','John','Mary','Bob','Alice'
    ]
}

pdf = pd.DataFrame(pivot_data)

In [58]:
pdf

          Date Product Region  Sales  Units    Rep
0   2023-01-01       A   East    450     25   John
1   2023-01-02       B   West    780     45   Mary
2   2023-01-03       C  North    320     18    Bob
3   2023-01-04       D  South    910     52  Alice
4   2023-01-05       A   East    560     31   John
5   2023-01-06       B   West    670     39   Mary
6   2023-01-07       C  North    230     15    Bob
7   2023-01-08       D  South    850     48  Alice
8   2023-01-09       A   East    490     28   John
9   2023-01-10       B   West    720     42   Mary
10  2023-01-11       C  North    380     21    Bob
11  2023-01-12       D  South    640     35  Alice
12  2023-01-13       A   East    590     33   John
13  2023-01-14       B   West    810     46   Mary
14  2023-01-15       C  North    270     17    Bob
15  2023-01-16       D  South    930     55  Alice
16  2023-01-17       A   East    410     24   John
17  2023-01-18       B   West    760     41   Mary
18  2023-01-19       C  North    350     20    Bob
19  2023-01-20       D  South    880     50  Alice

In [59]:
pd.pivot_table(pdf,values = 'Sales', index ='Region' , columns = 'Product',aggfunc = 'median' )

Product      A      B      C      D
Region
East     490.0    NaN    NaN    NaN
North      NaN    NaN  320.0    NaN
South      NaN    NaN    NaN  880.0
West       NaN  760.0    NaN    NaN

In [60]:
pivot2 = pd.pivot_table(pdf,values = ['Units','Sales'], index ='Region' , columns = 'Product',aggfunc = 'median' )
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     490.0    NaN    NaN    NaN  28.0   NaN   NaN   NaN
North      NaN    NaN  320.0    NaN   NaN   NaN  18.0   NaN
South      NaN    NaN    NaN  880.0   NaN   NaN   NaN  50.0
West       NaN  760.0    NaN    NaN   NaN  42.0   NaN   NaN

cross table

In [61]:
pd.crosstab(pdf['Region'],pdf['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

 operations 
 dataframe basics operation

In [62]:
odf = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

In [63]:
odf

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [64]:
odf.shape

(5, 3)

In [65]:
odf.columns

Index(['A', 'B', 'C'], dtype='str')

In [66]:
odf.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [67]:
odf.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [68]:
odf['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

DAtaframe applying function

In [69]:
def  square(x):
    return x**2

In [70]:
odf['B'] = odf['B'].apply(square)
odf

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

feature extraction for project

loading the data

In [93]:
dff=pd.read_csv(r'anime.csv')

In [94]:
dff

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

top 5 data ke liye head use karte hai

In [95]:
dff.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [96]:
dff.loc[3]

Rank                                                     4
Title    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
Score                                                 9.06
Name: 3, dtype: object

In [97]:
dff.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [112]:
def extracted_episodes(txt):
    start = txt.find('(')
    end = txt.find(')', start)

    if start != -1 and end != -1:
        episode = txt[start + 1:end].split()[0]
        if episode.isdigit():
            return int(episode)

    return None

In [113]:
dff["Episode"] = dff["Title"].apply(extracted_episodes)

In [116]:
dff[["Title", "Episode"]].head(10)

                                               Title  Episode
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...       64
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...       24
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...       13
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...       51
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...       10
5  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...       51
6  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...        1
7  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...      148
8  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...       13
9  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...       13

In [117]:
dff["Episode"] = dff["Episode"].astype(int)

In [118]:
dff.columns

Index(['Rank', 'Title', 'Score', 'Episode'], dtype='str')

In [119]:
dff

    Rank                                              Title  Score  Episode
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [120]:
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1, i+20):
                data += txt[j]

            return data

In [121]:
dff['Total Time'] = dff['Title'].apply(extraction_time)

dff.head()

,Rank,Title,Score,Episode,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [127]:
dff[dff['Score']==dff['Score'].max()]

,Rank,Title,Score,Episode,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [128]:
dff.head()

,Rank,Title,Score,Episode,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

data capstone project using countrie.csv file

In [130]:
dfc=pd.read_csv('countries.csv')

In [131]:
dfc

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [133]:
dfc.shape

(194, 64)

In [134]:
dfc.info

<bound method DataFrame.info of                 country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]>

In [136]:
dfc.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [140]:
dfc[dfc['population']==dfc['population'].max()]['country']

75    India
Name: country, dtype: str

In [141]:
dfc[dfc['population']==dfc['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: str

In [142]:
dfc[dfc['population']==dfc['population'].min()]['country']

179    Tuvalu
Name: country, dtype: str

In [144]:
dfc['region'].count

<bound method Series.count of 0           Southern Asia
1         Southern Europe
2         Northern Africa
3         Southern Europe
4           Middle Africa
              ...
189    South-Eastern Asia
190          Western Asia
191          Western Asia
192        Eastern Africa
193        Eastern Africa
Name: region, Length: 194, dtype: str>

In [149]:
dfc['region'].value_counts().count()

np.int64(22)

In [154]:
dfc[dfc['region'] == 'Southern Asia'].count()

country             9
country_long        9
currency            9
capital_city        9
region              9
                   ..
democracy_score     9
democracy_type      9
median_age          9
political_leader    9
title               9
Length: 64, dtype: int64

In [155]:
dfc[dfc['region'] == 'country'].count()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    0
title               0
Length: 64, dtype: int64

political leader of 2nd highest population country

In [159]:
dfc[dfc['population']==dfc['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: str

In [160]:
dfc[dfc['political_leader'].isna()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.500000,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.0,...,47657,31.2500,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.0,...,103948,18.1818,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
172,Timor-Leste,Democratic Republic of Timor-Leste,U.S. dollar,Dili,South-Eastern Asia,Asia,East Timorese,-8.833333,125.916667,3414.0,...,1341296,40.0000,911089,430207,2.61,7.19,Flawed democracy,16.7,NaN,NaN
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN

In [161]:
dfc[dfc['political_leader'].isna()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: str

In [168]:
dfc[dfc['continent'] == 'Africa']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.0,...,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.000000,30.000000,39710.0,...,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,...,1674908,31.00000,435309,1239599,1.34,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
56,Eswatini,Kingdom of Eswatini,Swazi lilangeni,Lobamba,Southern Africa,Africa,Swazi,-26.500000,31.500000,12220.0,...,1201670,13.51350,906348,295322,1.59,3.03,Authoritarian,17.7,Mswati III,King
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,...,2388992,15.38460,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,...,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.0,...,37457971,24.05060,13261620,24196351,1.78,4.99,Hybrid regime,25.0,Mohammed VI,King
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
118,Namibia,Republic of Namibia,Namibian dollar,Windhoek,Southern Africa,Africa,Namibian,-22.000000,17.000000,388100.0,...,2567012,44.23080,1181955,1385057,4.13,6.25,Flawed democracy,17.4,Hage Geingob,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,227380,14.54550,55128,172252,0.00,0.00,Unknown,14.6,Evaristo Carvalho,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.0,...,59893885,46.50000,18965399,40928486,3.52,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President
156,South Sudan,Republic of South Sudan,South Sudanese Pound,Juba,Middle Africa,Africa,South Sudanese,7.000000,30.000000,282510.0,...,10913164,32.36360,8638206,2274958,1.71,0.00,Unknown,12.5,Salva Kiir Mayardit,President
162,Sudan,Republic of the Sudan,Sudanese pound,Khartoum,Northern Africa,Africa,Sudanese,15.000000,30.000000,694058.0,...,46874204,30.51640,30020115,16854089,1.08,2.15,Authoritarian,14.5,Abdel Fattah al-Burhan,Leader of the Sovereignty Council
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
176,Tunisia,Republic of Tunisia,Tunisian dinar,Tunis,Northern Africa,Africa,Tunisian,34.000000,9.000000,97310.0,...,12356117,26.26730,3680393,8675724,2.64,6.41,Flawed democracy,28.0,Kaïs Saïed,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

how many countries have republic in theri name

In [177]:
count = 0

def counting(txt):
    global count
    if 'republic' in txt.lower():
        count += 1
    return txt

dfc['country'] = dfc['country'].apply(counting)

print(count)

6